(define (frame->painter frame)
  (let ((l1 (make-segment (frame-origin frame) (frame-edge1 frame)))
        (l2 (make-segment (frame-origin frame) (frame-edge2 frame)))
        (l3 (make-segment (frame-edge1 frame) (vector-sub (vector-add (frame-edge1 frame)
                                                                      (frame-edge2 frame))
                                                          (frame-origin frame))))
        (l4 (make-segment (frame-edge2 frame) (vector-sub (vector-add (frame-edge1 frame)
                                                                      (frame-edge2 frame))
                                                          (frame-origin frame)))))
    (segments->painter (list l1 l2 l3 l4))))
