(define (make-account balance secret-number)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount)) balance)
        "insufficient funds"))
  (define (deposit amount)
    (begin (set! balance (+ balance amount)) balance))
  (define input-counts 0)
  (define (dispatch password m)
    (if (eq? password secret-number)
        (begin (set! input-counts 0)
               (cond ((eq? m 'withdraw) withdraw)
                     ((eq? m 'deposit) deposit)
                     (else "no such requests")))
        (begin (set! input-counts (+ input-counts 1))
               (cond ((> input-counts 2) (error "We have called the cops!!!!"))
                     (else (error "incorrect password,please retry --PASSWORD" password))))))
  dispatch)
